# Generated by Django 4.0.2 on 2022-02-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='works_with_discount',
            field=models.BooleanField(default=False),
        ),
    ]
