# Generated by Django 4.0.2 on 2022-02-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_promocode_works_with_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='promocode',
            new_name='promo_code',
        ),
    ]
