# Generated by Django 4.0.2 on 2022-02-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_productincart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
