# Generated by Django 4.0.2 on 2022-03-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_notificationperiod_order_execution_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationperiod',
            name='minutes',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
